$(document).ready(function(){
  $(".down").click(function(){
    $(".user").toggleClass("t100");
    $(this).toggle();
    $(".up").toggle();
  })
  $(".up").click(function(){
    $(".user").toggleClass("t100");
    $(this).toggle();
    $(".down").toggle();
  })
  $(".menu-icon").click(()=>{
    $(".sidebar").toggleClass("menuclick");
    if($(window).width()>768){
    $(".main").toggleClass("ml0");
    }
  })
  if($(window).width()< 768){
    $(".sidebar-item>li").click(()=>{
      $(".sidebar").toggleClass("menuclick")
    })
  }
  $(".sidebar-donation").click(()=>{
    $.ajax({
      url:"donation.php",
      success:(e)=>{
      $("#main").html(e);
      
      }
    })
  })
  $(".sidebar-volenteer").click(()=>{
    $.ajax({
      url:"volenteer.php",
      success:(e)=>{
        $("#main").html(e);
      }
    })
  })
  $(".sidebar-subscriber").click(()=>{
    $.ajax({
      url:"subscriber.php",
      success:(e)=>{
        $("#main").html(e);
      }
    })
  })
  ajax_pagination=(i,page)=>{
    $.ajax({
      url:page+"?page="+i,
      success:(e)=>{
        $("#main").html(e);

      }
    })
  }
})
